export const TYPES = {
  ember: {
    name: "Emberling",
    role: "SPLASH",
    tip: "Burns clustered foes",
    color: 0xff9054,
    hp: 17,
    speed: 2.2,
    damage: 9,
    rate: 0.9,
    power: 13,
    range: 11,
    shape: "ember",
  },
  thorn: {
    name: "Thornback",
    role: "WARD",
    tip: "Shields you; shoves crowds",
    color: 0xb7cd88,
    hp: 38,
    speed: 1.65,
    damage: 12,
    rate: 1.6,
    power: 16,
    range: 5,
    shape: "thorn",
  },
  volt: {
    name: "Voltwing",
    role: "CHAIN",
    tip: "Lightning jumps between foes",
    color: 0x9fc7ff,
    hp: 16,
    speed: 3.15,
    damage: 7,
    rate: 1.05,
    power: 11,
    range: 13,
    shape: "volt",
  },
  mire: {
    name: "Mireling",
    role: "SLOW",
    tip: "Poisons and slows an area",
    color: 0xb596df,
    hp: 23,
    speed: 1.7,
    damage: 8,
    rate: 1.6,
    power: 9,
    range: 14,
    shape: "mire",
  },
  fang: {
    name: "Fangling",
    role: "HUNT",
    tip: "Pounces on strong targets",
    color: 0xeab6ad,
    hp: 24,
    speed: 2.9,
    damage: 13,
    rate: 1.05,
    power: 28,
    range: 14,
    shape: "fang",
  },
  moth: {
    name: "Mourning Moth",
    role: "MEND",
    tip: "Restores health while fighting",
    color: 0xffe6a3,
    hp: 19,
    speed: 2.4,
    damage: 6,
    rate: 2.4,
    power: 7,
    range: 11,
    shape: "moth",
  },
  pyre: {
    name: "Pyre Warden",
    role: "INFERNO + WARD",
    tip: "Sweeping fire, reinforced protection",
    color: 0xffb056,
    rate: 1.2,
    power: 66,
    range: 13,
    tier: 1,
    shape: "thorn",
  },
  storm: {
    name: "Storm Serpent",
    role: "CHAIN + SLOW",
    tip: "Wide lightning web holds the horde",
    color: 0x91dbf2,
    rate: 1,
    power: 43,
    range: 17,
    tier: 1,
    shape: "volt",
  },
  dusk: {
    name: "Dusk Reaper",
    role: "EXECUTE + MEND",
    tip: "Hunts elites and heals the keeper",
    color: 0xe3b4f1,
    rate: 0.8,
    power: 100,
    range: 16,
    tier: 1,
    shape: "fang",
  },
  solar: {
    name: "Solar Seraph",
    role: "DAWN ERUPTION",
    tip: "The whole ring burns. You recover",
    color: 0xffe29c,
    rate: 1.3,
    power: 180,
    range: 20,
    tier: 2,
    shape: "moth",
  },
  world: {
    name: "Worldcoil",
    role: "TEMPEST DOMINION",
    tip: "Storm chains sweep and pin entire packs",
    color: 0xa3ffde,
    rate: 1,
    power: 130,
    range: 22,
    tier: 2,
    shape: "volt",
  },
  eclipse: {
    name: "Eclipse Sovereign",
    role: "NIGHTFALL",
    tip: "Devours dangerous foes and their shadows",
    color: 0xe5beff,
    rate: 0.75,
    power: 270,
    range: 22,
    tier: 2,
    shape: "fang",
  },
  boss: {
    name: "The Bellkeeper",
    role: "FINAL BOSS",
    color: 0xceb5ce,
    hp: 4200,
    speed: 1.2,
    damage: 20,
    shape: "boss",
  },
};
export const BASE = ["ember", "thorn", "volt", "mire", "fang", "moth"];
export const RECIPES = [
  { result: "pyre", needs: ["ember", "thorn"], wave: 5 },
  { result: "storm", needs: ["volt", "mire"], wave: 5 },
  { result: "dusk", needs: ["fang", "moth"], wave: 5 },
  { result: "solar", needs: ["pyre", "volt", "moth"], wave: 10 },
  { result: "world", needs: ["storm", "thorn", "fang"], wave: 10 },
  { result: "eclipse", needs: ["dusk", "ember", "mire"], wave: 10 },
];
export const WAVES = [
  ["The first light", ["ember"], 1.3],
  ["Something stirs", ["ember", "thorn", "volt"], 2],
  ["The mire wakes", ["ember", "thorn", "volt", "mire", "fang"], 2.8],
  ["Hold the circle", ["ember", "thorn", "volt", "mire", "fang", "moth"], 5.2],
  ["First awakening", BASE, 4.2],
  ["Teeth in the mist", ["fang", "mire", "ember", "moth"], 5.3],
  ["Wing and thorn", ["volt", "thorn", "moth", "ember"], 6],
  ["A gathering dark", BASE, 7],
  ["Before the dawn", BASE, 10],
  ["The great ascension", BASE, 8],
  ["The last procession", BASE, 11],
  ["The Bellkeeper", BASE, 5],
];
export const DEFAULTS = {
  waveSeconds: 22,
  chargeSeconds: 11,
  captureRange: 13,
  evolutionScale: 1,
  enemyCap: 240,
  lateWaveRate: 18,
};
